# Generated by Django 5.2.6 on 2025-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.TextField(blank=True),
        ),
    ]
