# Generated by Django 5.2.6 on 2025-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='residential_apartment_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_street_number',
            field=models.TextField(),
        ),
    ]
