# Generated by Django 5.2.6 on 2025-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_residential_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateTimeField(null=True),
        ),
    ]
