# Generated by Django 5.2.6 on 2025-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0004_alter_voter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.TextField(),
        ),
    ]
